/* tslint:disable */
/* eslint-disable */
/**
 * Ordering API (minimal)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetHealth200Response,
  OrderingRulesResponse,
  PricingResolveResponse,
} from '../models/index';
import {
    GetHealth200ResponseFromJSON,
    GetHealth200ResponseToJSON,
    OrderingRulesResponseFromJSON,
    OrderingRulesResponseToJSON,
    PricingResolveResponseFromJSON,
    PricingResolveResponseToJSON,
} from '../models/index';

export interface ResolveOrderingRulesRequest {
    vendorId: string;
    storeId: string;
    date: Date;
}

export interface ResolvePricingRequest {
    vendorId: string;
    itemId: string;
    date: Date;
    storeId?: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Health check
     */
    async getHealthRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetHealth200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetHealth200ResponseFromJSON(jsonValue));
    }

    /**
     * Health check
     */
    async getHealth(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetHealth200Response> {
        const response = await this.getHealthRaw(initOverrides);
        return await response.value();
    }

    /**
     * Resolve orderable/cutoff/lead time by vendor/store/date
     */
    async resolveOrderingRulesRaw(requestParameters: ResolveOrderingRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<OrderingRulesResponse>> {
        if (requestParameters['vendorId'] == null) {
            throw new runtime.RequiredError(
                'vendorId',
                'Required parameter "vendorId" was null or undefined when calling resolveOrderingRules().'
            );
        }

        if (requestParameters['storeId'] == null) {
            throw new runtime.RequiredError(
                'storeId',
                'Required parameter "storeId" was null or undefined when calling resolveOrderingRules().'
            );
        }

        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling resolveOrderingRules().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['vendorId'] != null) {
            queryParameters['vendorId'] = requestParameters['vendorId'];
        }

        if (requestParameters['storeId'] != null) {
            queryParameters['storeId'] = requestParameters['storeId'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = (requestParameters['date'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/ordering/rules`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrderingRulesResponseFromJSON(jsonValue));
    }

    /**
     * Resolve orderable/cutoff/lead time by vendor/store/date
     */
    async resolveOrderingRules(requestParameters: ResolveOrderingRulesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<OrderingRulesResponse> {
        const response = await this.resolveOrderingRulesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Resolve unit price by vendor/item/(store)/date
     */
    async resolvePricingRaw(requestParameters: ResolvePricingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PricingResolveResponse>> {
        if (requestParameters['vendorId'] == null) {
            throw new runtime.RequiredError(
                'vendorId',
                'Required parameter "vendorId" was null or undefined when calling resolvePricing().'
            );
        }

        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling resolvePricing().'
            );
        }

        if (requestParameters['date'] == null) {
            throw new runtime.RequiredError(
                'date',
                'Required parameter "date" was null or undefined when calling resolvePricing().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['vendorId'] != null) {
            queryParameters['vendorId'] = requestParameters['vendorId'];
        }

        if (requestParameters['itemId'] != null) {
            queryParameters['itemId'] = requestParameters['itemId'];
        }

        if (requestParameters['storeId'] != null) {
            queryParameters['storeId'] = requestParameters['storeId'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = (requestParameters['date'] as any).toISOString().substring(0,10);
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/pricing/resolve`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PricingResolveResponseFromJSON(jsonValue));
    }

    /**
     * Resolve unit price by vendor/item/(store)/date
     */
    async resolvePricing(requestParameters: ResolvePricingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PricingResolveResponse> {
        const response = await this.resolvePricingRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
