/* tslint:disable */
/* eslint-disable */
/**
 * Ordering API (minimal)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetHealth200Response
 */
export interface GetHealth200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetHealth200Response
     */
    ok?: boolean;
}

/**
 * Check if a given object implements the GetHealth200Response interface.
 */
export function instanceOfGetHealth200Response(value: object): value is GetHealth200Response {
    return true;
}

export function GetHealth200ResponseFromJSON(json: any): GetHealth200Response {
    return GetHealth200ResponseFromJSONTyped(json, false);
}

export function GetHealth200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHealth200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'ok': json['ok'] == null ? undefined : json['ok'],
    };
}

export function GetHealth200ResponseToJSON(json: any): GetHealth200Response {
    return GetHealth200ResponseToJSONTyped(json, false);
}

export function GetHealth200ResponseToJSONTyped(value?: GetHealth200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ok': value['ok'],
    };
}

