/* tslint:disable */
/* eslint-disable */
/**
 * Ordering API (minimal)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderingRulesResponse
 */
export interface OrderingRulesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof OrderingRulesResponse
     */
    orderable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrderingRulesResponse
     */
    cutoffHHmm?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderingRulesResponse
     */
    leadTimeDays?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderingRulesResponse
     */
    source?: OrderingRulesResponseSourceEnum;
}


/**
 * @export
 */
export const OrderingRulesResponseSourceEnum = {
    Calendar: 'calendar',
    Override: 'override',
    Vendor: 'vendor'
} as const;
export type OrderingRulesResponseSourceEnum = typeof OrderingRulesResponseSourceEnum[keyof typeof OrderingRulesResponseSourceEnum];


/**
 * Check if a given object implements the OrderingRulesResponse interface.
 */
export function instanceOfOrderingRulesResponse(value: object): value is OrderingRulesResponse {
    return true;
}

export function OrderingRulesResponseFromJSON(json: any): OrderingRulesResponse {
    return OrderingRulesResponseFromJSONTyped(json, false);
}

export function OrderingRulesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderingRulesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderable': json['orderable'] == null ? undefined : json['orderable'],
        'cutoffHHmm': json['cutoffHHmm'] == null ? undefined : json['cutoffHHmm'],
        'leadTimeDays': json['leadTimeDays'] == null ? undefined : json['leadTimeDays'],
        'source': json['source'] == null ? undefined : json['source'],
    };
}

export function OrderingRulesResponseToJSON(json: any): OrderingRulesResponse {
    return OrderingRulesResponseToJSONTyped(json, false);
}

export function OrderingRulesResponseToJSONTyped(value?: OrderingRulesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderable': value['orderable'],
        'cutoffHHmm': value['cutoffHHmm'],
        'leadTimeDays': value['leadTimeDays'],
        'source': value['source'],
    };
}

