/* tslint:disable */
/* eslint-disable */
/**
 * Ordering API (minimal)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TempZone } from './TempZone';
import {
    TempZoneFromJSON,
    TempZoneFromJSONTyped,
    TempZoneToJSON,
    TempZoneToJSONTyped,
} from './TempZone';

/**
 * 
 * @export
 * @interface PricingResolveResponse
 */
export interface PricingResolveResponse {
    /**
     * 
     * @type {number}
     * @memberof PricingResolveResponse
     */
    unitPrice?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof PricingResolveResponse
     */
    validFrom?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PricingResolveResponse
     */
    validTo?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PricingResolveResponse
     */
    source?: PricingResolveResponseSourceEnum;
    /**
     * 
     * @type {TempZone}
     * @memberof PricingResolveResponse
     */
    tempZone?: TempZone;
}


/**
 * @export
 */
export const PricingResolveResponseSourceEnum = {
    Store: 'store',
    Vendor: 'vendor',
    None: 'none'
} as const;
export type PricingResolveResponseSourceEnum = typeof PricingResolveResponseSourceEnum[keyof typeof PricingResolveResponseSourceEnum];


/**
 * Check if a given object implements the PricingResolveResponse interface.
 */
export function instanceOfPricingResolveResponse(value: object): value is PricingResolveResponse {
    return true;
}

export function PricingResolveResponseFromJSON(json: any): PricingResolveResponse {
    return PricingResolveResponseFromJSONTyped(json, false);
}

export function PricingResolveResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricingResolveResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'unitPrice': json['unitPrice'] == null ? undefined : json['unitPrice'],
        'validFrom': json['validFrom'] == null ? undefined : (new Date(json['validFrom'])),
        'validTo': json['validTo'] == null ? undefined : (new Date(json['validTo'])),
        'source': json['source'] == null ? undefined : json['source'],
        'tempZone': json['tempZone'] == null ? undefined : TempZoneFromJSON(json['tempZone']),
    };
}

export function PricingResolveResponseToJSON(json: any): PricingResolveResponse {
    return PricingResolveResponseToJSONTyped(json, false);
}

export function PricingResolveResponseToJSONTyped(value?: PricingResolveResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unitPrice': value['unitPrice'],
        'validFrom': value['validFrom'] === null ? null : ((value['validFrom'] as any)?.toISOString().substring(0,10)),
        'validTo': value['validTo'] === null ? null : ((value['validTo'] as any)?.toISOString().substring(0,10)),
        'source': value['source'],
        'tempZone': TempZoneToJSON(value['tempZone']),
    };
}

