/* tslint:disable */
/* eslint-disable */
/**
 * Ordering API (minimal)
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TempZone = {
    Ambient: 'ambient',
    Chilled: 'chilled',
    Frozen: 'frozen'
} as const;
export type TempZone = typeof TempZone[keyof typeof TempZone];


export function instanceOfTempZone(value: any): boolean {
    for (const key in TempZone) {
        if (Object.prototype.hasOwnProperty.call(TempZone, key)) {
            if (TempZone[key as keyof typeof TempZone] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TempZoneFromJSON(json: any): TempZone {
    return TempZoneFromJSONTyped(json, false);
}

export function TempZoneFromJSONTyped(json: any, ignoreDiscriminator: boolean): TempZone {
    return json as TempZone;
}

export function TempZoneToJSON(value?: TempZone | null): any {
    return value as any;
}

export function TempZoneToJSONTyped(value: any, ignoreDiscriminator: boolean): TempZone {
    return value as TempZone;
}

